#!/usr/bin/env sh
# Portable better sudo completion (bash + zsh)

better_sudo() {
    # Detect shell reliably
    if [ -n "$BASH_VERSION" ]; then
        _shell="bash"
    elif [ -n "$ZSH_VERSION" ]; then
        _shell="zsh"
    else
        _shell="unknown"
    fi

    case "$_shell" in
        bash)
            complete -cf sudo
            ;;
        zsh)
            autoload -Uz compinit
            compinit

            autoload -Uz bashcompinit
            bashcompinit

            complete -cf sudo
            ;;
        *)
            printf "better_sudo: unsupported shell\n" >&2
            return 1
            ;;
    esac
}

better_sudo "$@"
