#!/usr/bin/env sh
# SSH with automatic tmux connection, fails over to normal shell if no tmux is present
# This one-liner does:
# - Checks if tmux is present
# - Attaches or connects to tmux
# - If tmux is not present, starts a normal shell

better_ssh() {
    /usr/bin/ssh "$@" -t /bin/sh "
        # Check if tmux exists on the remote machine
        command -v tmux >/dev/null 2>&1 \
        # If tmux does NOT exist, try to start tmux
        || tmux new -A -s \"\$(whoami)\" \
        # If tmux fails, fall back to the user's default shell
        || exec \"\$SHELL\" -l
    "
}

# Call main function
better_ssh "$@"
