#!/bin/bash
# SSH with automatic tmux connection, fails over to normal shell if no tmux is present
# This one liner does:
# - Checks if tmux is present
# - Attachs or connnects to tmux
# - If tmux is not present, starts a normal shell

function better_ssh()
{
    /usr/bin/ssh "$@" -t /bin/sh "command -v tmux &>/dev/null || tmux new -A -s $(whoami) || $SHELL -l"
}

# Call main function
better_ssh "$@"
