#!/bin/bash
##==============================================================================
##  Alias general config
##==============================================================================
# Enabling Alias expansion, to use them in vim
shell="bash"
# shellcheck disable=SC2009
if [[ $(ps -p $$ | grep sh | awk '{print $(NF)}') = "$shell" ]]; then
   shopt -s expand_aliases
fi

# Improving readability options with:
# - Color coding
# - Human readable
# - Nicer sorting/behavior
# - Avoid preexisting Alias prefixing \ to de command, just in case
alias grep='rg --color=auto'
alias tree='\tree --dirsfirst -C'
alias dmesg='\dmesg --color=auto --reltime --human --nopager --decode'
alias free='\free -mht'
alias du='\du -h'
alias df='\df -h'

# Setting Alias for enhanced commands
alias ls='better-ls'
alias history='better-history'
alias ssh='better-ssh'
alias sudo='better-sudo'

# Reload rc files
alias brc='UNSET BASE_CONFIG_LOADED && source ~/.bashrc'
alias zrc='source ~/.zshrc'
alias trc='tmux source-file ~/.tmux.conf'

# navigation
alias ..='cd ..'
alias ...='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'
alias .6='cd ../../../../../..'

# Python env

# Utils
alias rmotd='run-parts /etc/update-motd.d/'
alias myip="curl http://ipecho.net/plain; echo"
alias fixbt="sudo rmmod btusb && sudo modprobe btusb"
alias nvdot="cd ~/.config/nvim && nvim ."

# Github cli
alias gc='gh copilot'
alias gcs='gh copilot suggest'
alias gce='gh copilot explain'
